import torch
import torch.nn as nn
import math
import copy


class MFA(nn.Module):
    def __init__(self, n_components, n_channels, n_factors, tol=1e-4, max_iter=150, device='cpu', alpha=0.6):
        super().__init__()
        self.K = n_components
        self.D = n_channels
        self.q = n_factors
        self.tol = tol
        self.max_iter = max_iter
        self.device = device
        self.alpha = alpha
        
        # Initialize parameters
        self.log_pi = nn.Parameter(torch.log(torch.ones(self.K, device=self.device) / self.K))
        # Initialize means centered around 0 but spread out
        self.mu = nn.Parameter(torch.randn(self.K, self.D, device=self.device) * 0.1)
        # Factor loadings (K, D, q)
        self.Lambda = nn.Parameter(torch.randn(self.K, self.D, self.q, device=self.device) * 0.1)
        # Log Diagonal noise is specific to each component (K, D)
        self.log_psi = nn.Parameter(torch.log(torch.ones(self.K, self.D, device=self.device) * 1e-2))

        # We use register_buffer so they are saved in the state_dict but aren't trainable parameters
        self.register_buffer('S0', torch.zeros(self.K, device=self.device))
        self.register_buffer('S1', torch.zeros(self.K, self.D, device=self.device))
        self.register_buffer('S_xx', torch.zeros(self.K, self.D, device=self.device))      # Diagonal only!
        self.register_buffer('S_z', torch.zeros(self.K, self.q, device=self.device))
        self.register_buffer('S_xz', torch.zeros(self.K, self.D, self.q, device=self.device))
        self.register_buffer('S_zz', torch.zeros(self.K, self.q, self.q, device=self.device))

        self.register_buffer('update_counts', torch.zeros(self.K, device=self.device))
        
    def fit(self, X, n_init=5):
        """
        Fits the MFA model using Multiple Restarts to ensure robust convergence.
        """
        X = X.to(self.device)
        N = X.shape[0]
        
        best_ll = -float('inf')
        best_state = None

        for init_run in range(n_init):
            # Reset and scientifically initialize parameters
            self._initialize_parameters(X)
            
            prev_ll = -float('inf')
            
            with torch.no_grad():
                for i in range(self.max_iter):
                    log_resp_norm, log_likelihood, _, _ = self.e_step(X)
                    current_ll = log_likelihood.mean()
                    
                    resp = torch.exp(log_resp_norm) 
                    self.m_step(X, resp)
                    
                    diff = current_ll - prev_ll
                    if i > 0 and abs(diff) < self.tol:
                        break
                    prev_ll = current_ll
                    
                final_ll = prev_ll * N 
                
                # Keep track of the best run
                if final_ll > best_ll:
                    best_ll = final_ll
                    # Deep copy the state dict so it doesn't get overwritten
                    best_state = copy.deepcopy(self.state_dict())
                    
        # Restore the weights of the best run
        if best_state is not None:
            self.load_state_dict(best_state)
            self.final_ll = best_ll
            # Calculating sufficient statistics from the best fit for future online updates
            with torch.no_grad():
                log_resp_norm, _, _, _ = self.e_step(X)
                resp = torch.exp(log_resp_norm)
                self.S0 = resp.sum(dim=0)
                self.S1 = resp.T @ X
                self.S_xx = resp.T @ (X ** 2) 
                
                # E-step for latent variables to compute S_z, S_xz, S_zz
                for k in range(self.K):
                    resp_k = resp[:, k].unsqueeze(1) 
                    L_k = self.Lambda[k]                      
                    mu_k = self.mu[k]                         
                    inv_psi = 1.0 / (torch.exp(self.log_psi[k]) + 1e-6) 

                    L_k_scaled = inv_psi.unsqueeze(1) * L_k                   
                    M = torch.eye(self.q, device=self.device) + L_k.T @ L_k_scaled
                    inv_M = torch.inverse(M)                                  
                    beta = inv_M @ L_k_scaled.T                               

                    diff = X - mu_k                                           
                    Ez = diff @ beta.T                                        # E[z|x] -> (N, q)

                    self.S_z[k] = (resp_k * Ez).sum(dim=0)
                    self.S_xz[k] = (resp_k * X).T @ Ez
                    self.S_zz[k] = (resp_k * Ez).T @ Ez
                    
        
    def e_step(self, X):
        """
        Performs the Expectation step.
        
        Returns:
        - log_resp_norm: (N, K) tensor. The normalized log responsibilities, 
          log(h_ij). This is the log posterior probability that data point i 
          was generated by cluster j: log(P(w_j|x_i)) = log_resps - log_likelihood
          
        - log_likelihood: (N) tensor. The total log marginal likelihood of 
          each data point across the entire mixture model, log(P(x_i)). 
          Summing this tensor gives the objective function the EM algorithm maximizes.
          
        - log_probs: (N, K) tensor. The conditional log-likelihood of the data 
          under each specific component j, log(P(x_i | w_j)). This is evaluated 
          using the local covariance structure \Lambda_j\Lambda_j' + \Psi.
          
        - mahalanobis_dists: (N, K) tensor. The squared Mahalanobis distance 
          between each data point x_i and each cluster mean \mu_j, accounting 
          for the local dimensionality reduction metric.
        """
        log_probs, mahalanobis_dists = self.compute_distances_and_log_probs(X)
        log_resps = log_probs + self.log_pi.unsqueeze(0)
        log_likelihood = torch.logsumexp(log_resps, dim=1)
        log_resp_norm = log_resps - log_likelihood.unsqueeze(1)
        
        return log_resp_norm, log_likelihood, log_probs, mahalanobis_dists

    def m_step(self, X, resp):
        N, D = X.shape
        Nk = resp.sum(dim=0) + 1e-10 
        
        # 1. Update Global Mixing Weights (Pi)
        self.log_pi.data = torch.log(Nk / N)
        
        for k in range(self.K):
            resp_k = resp[:, k].unsqueeze(1) # (N, 1)
            
            L_k = self.Lambda[k]                      # (D, q)
            mu_k = self.mu[k]                         # (D,)
            psi_k = torch.exp(self.log_psi[k]) + 1e-6 # (D,)
            inv_psi = 1.0 / psi_k                     # (D,)
            
            # M = I + L^T * Psi^{-1} * L
            L_k_scaled = inv_psi.unsqueeze(1) * L_k                   
            M = torch.eye(self.q, device=self.device) + L_k.T @ L_k_scaled
            inv_M = torch.inverse(M)                                  
            
            # beta = M^{-1} * L^T * Psi^{-1}
            beta = inv_M @ L_k_scaled.T                               # (q, D)
            
            # First Moment: E[z | x] = beta * (X - mu)
            diff = X - mu_k                                           # (N, D)
            Ez = diff @ beta.T                                        # (N, q)
            
            # Second Moment Summation: sum(h_ij * E[zz^T]) 
            # Var(z|x) elegantly reduces to exactly inv_M
            sum_Ezz = Nk[k] * inv_M + Ez.T @ (resp_k * Ez)            # (q, q)
            
            # Augmented latent factor: Ez_tilde = [Ez, 1] 
            ones = torch.ones(N, 1, device=self.device)
            Ez_tilde = torch.cat([Ez, ones], dim=1)                   # (N, q+1)
            
            # sum_i h_{ij} E[z_tilde z_tilde^T]
            sum_h_Ez = (resp_k * Ez).sum(dim=0, keepdim=True).T       # (q, 1)
            
            top_row = torch.cat([sum_Ezz, sum_h_Ez], dim=1)           
            bottom_row = torch.cat([sum_h_Ez.T, Nk[k].unsqueeze(0).unsqueeze(0)], dim=1) 
            sum_E_ztilde_ztildeT = torch.cat([top_row, bottom_row], dim=0) # (q+1, q+1)
            
            # sum_i h_{ij} x_i Ez_tilde^T -> shape (D, q+1)
            sum_x_Eztilde = (resp_k * X).T @ Ez_tilde                 # (D, q+1)
            
            # Lambda_tilde_new = sum_x_Eztilde @ inv(sum_E_ztilde_ztildeT)
            Lambda_tilde_new = sum_x_Eztilde @ torch.inverse(sum_E_ztilde_ztildeT)       
            
            Lambda_new = Lambda_tilde_new[:, :self.q]                 # (D, q)
            mu_new = Lambda_tilde_new[:, self.q]                      # (D,)
            
            # Psi_new = diag( sum_i h_ij (x_i x_i^T - Lambda_tilde_new E_ztilde_i x_i^T) ) / Nk[k]
            diag_xx = (resp_k * X * X).sum(dim=0)                     # (D,)
            
            # The cross term simplifies to row-wise multiplication, avoiding O(D^2) memory allocations
            diag_cross = (Lambda_tilde_new * sum_x_Eztilde).sum(dim=1) # (D,)
            
            psi_update = (diag_xx - diag_cross) / Nk[k]
            psi_update = torch.clamp(psi_update, min=1e-5)
            
            self.Lambda.data[k] = Lambda_new
            self.mu.data[k] = mu_new
            self.log_psi.data[k] = torch.log(psi_update)


    def stepwise_em_update(self, X, log_resp):
        X = X.to(self.device)
        N = X.shape[0]
        resp = torch.exp(log_resp) # (N, K)

        # 1. Batch Responsibilities
        s0_batch = resp.sum(dim=0) / N                             # (K,)
        s1_batch = (resp.T @ X) / N                                # (K, D)
        s_xx_batch = (resp.T @ (X ** 2)) / N                       # (K, D) - Diagonal only!

        for k in range(self.K):
            if s0_batch[k] < 1e-6:
                continue
            
            resp_k = resp[:, k].unsqueeze(1) # (N, 1)

            # --- E-STEP for Latent Variables ---
            L_k = self.Lambda[k]                      
            mu_k = self.mu[k]                         
            inv_psi = 1.0 / (torch.exp(self.log_psi[k]) + 1e-6) 

            L_k_scaled = inv_psi.unsqueeze(1) * L_k                   
            M = torch.eye(self.q, device=self.device) + L_k.T @ L_k_scaled
            inv_M = torch.inverse(M)                                  
            beta = inv_M @ L_k_scaled.T                               

            diff = X - mu_k                                           
            Ez = diff @ beta.T                                        # E[z|x] -> (N, q)

            # --- Calculate Batch Sufficient Statistics ---
            sz_batch = (resp_k * Ez).sum(dim=0) / N                   # (q,)
            sxz_batch = ((resp_k * X).T @ Ez) / N                     # (D, q)

            # E[zz^T|x] summation
            sum_Ezz = (s0_batch[k] * N) * inv_M + Ez.T @ (resp_k * Ez)
            szz_batch = sum_Ezz / N                                   # (q, q)

            # --- Interpolate Global Sufficient Statistics ---
            k_count = self.update_counts[k].item()
            eta = (k_count + 2) ** (-self.alpha)

            if k_count == 0:
                self.S0[k] = s0_batch[k]
                self.S1[k] = s1_batch[k]
                self.S_xx[k] = s_xx_batch[k]
                self.S_z[k] = sz_batch
                self.S_xz[k] = sxz_batch
                self.S_zz[k] = szz_batch
            else:
                self.S0[k] = (1 - eta) * self.S0[k] + eta * s0_batch[k]
                self.S1[k] = (1 - eta) * self.S1[k] + eta * s1_batch[k]
                self.S_xx[k] = (1 - eta) * self.S_xx[k] + eta * s_xx_batch[k]
                self.S_z[k] = (1 - eta) * self.S_z[k] + eta * sz_batch
                self.S_xz[k] = (1 - eta) * self.S_xz[k] + eta * sxz_batch
                self.S_zz[k] = (1 - eta) * self.S_zz[k] + eta * szz_batch

            self.update_counts[k] += 1

            # --- M-STEP: Recover Parameters ---
            self.log_pi.data = torch.log(self.S0 / self.S0.sum() + 1e-10)

            mu_k_new = self.S1[k] / (self.S0[k] + 1e-10)
            self.mu.data[k] = mu_k_new

            # Exact Lambda update: (S_xz - mu * S_z^T) * S_zz^-1
            S_z_scaled = self.S_z[k].unsqueeze(0) # (1, q)
            mu_k_col = mu_k_new.unsqueeze(1)      # (D, 1)

            lambda_num = self.S_xz[k] - (mu_k_col @ S_z_scaled)
            Lambda_new = lambda_num @ torch.inverse(self.S_zz[k] + torch.eye(self.q, device=self.device)*1e-6)
            self.Lambda.data[k] = Lambda_new

            # Exact Psi update (diagonal only)
            diag_cross = (Lambda_new * lambda_num).sum(dim=1)

            # Add a ridge penalty (Tikhonov regularization) to prevent variance collapse
            ridge_penalty = 1e-6 

            psi_update = (self.S_xx[k] - (mu_k_new * self.S1[k]) - diag_cross + ridge_penalty) / (self.S0[k] + 1e-10)

            # You can keep the clamp as an absolute fail-safe
            self.log_psi.data[k] = torch.log(torch.clamp(psi_update, min=1e-5))
    
    def compute_distances_and_log_probs(self, X):
        """
        Calculates the pure structural/geometric fit using the Woodbury Matrix Identity
        to avoid O(D^3) inversion. 
        Fully vectorized across all K components to eliminate Python loops.
        """
        N, D = X.shape
        c = D * math.log(2 * math.pi)
        
        # 1. Prepare component-specific variances
        psi = torch.exp(self.log_psi) + 1e-6            # (K, D)
        inv_psi = 1.0 / psi                             # (K, D)
        
        # 2. Scale factor loadings for all K
        # self.Lambda is (K, D, q), inv_psi is (K, D)
        L_scaled = inv_psi.unsqueeze(-1) * self.Lambda  # (K, D, q)
        
        # 3. Compute M = I + Lambda^T * Psi^{-1} * Lambda for all K
        M_inner = self.Lambda.mT @ L_scaled             # (K, q, q)
        M = torch.eye(self.q, device=self.device).expand(self.K, -1, -1) + M_inner
        inv_M = torch.inverse(M)                        # (K, q, q)
        
        # 4. Compute Log Determinants for all K
        log_det_psi = torch.sum(torch.log(psi), dim=1)  # (K,)
        log_det_M = torch.logdet(M)                     # (K,)
        log_det_C = log_det_psi + log_det_M             # (K,)
        
        # 5. Compute Term 1 of Mahalanobis distance
        # To avoid creating a massive (N, K, D) tensor for (X - mu), we mathematically
        # expand the squared difference: (x - mu)^2 / psi = (x^2 / psi) - (2x * mu / psi) + (mu^2 / psi)
        X_sq = X ** 2                                   # (N, D)
        T1_A = X_sq @ inv_psi.T                         # (N, K)
        T1_B = X @ (self.mu * inv_psi).T                # (N, K)
        T1_C = torch.sum((self.mu ** 2) * inv_psi, dim=1) # (K,)
        
        term1 = T1_A - 2 * T1_B + T1_C                  # (N, K)
        
        # 6. Compute Term 2 using batched projections
        # proj = (X - mu) @ L_scaled 
        X_proj = torch.einsum('nd,kdq->nkq', X, L_scaled)       # (N, K, q)
        mu_proj = torch.einsum('kd,kdq->kq', self.mu, L_scaled) # (K, q)
        proj = X_proj - mu_proj.unsqueeze(0)                    # (N, K, q)
        
        # term2 = proj @ inv_M @ proj^T
        proj_invM = torch.einsum('nkq,kqr->nkr', proj, inv_M)   # (N, K, q)
        term2 = torch.sum(proj_invM * proj, dim=2)              # (N, K)
        
        # 7. Final outputs
        mahalanobis = term1 - term2                                     # (N, K)
        log_probs = -0.5 * (c + log_det_C.unsqueeze(0) + mahalanobis)   # (N, K)
        
        return log_probs, mahalanobis
        
    def add_components(self, X_valid, assignments, total_samples_seen, new_mu, new_Lambda, new_log_psi):
        """
        Dynamically adds MULTIPLE new components to the Mixture Model at once.
        Calculates sufficient statistics in a fully vectorized manner.
        """
        with torch.no_grad():
            K_new = new_mu.shape[0]
            q_new = new_Lambda.shape[2]
            
            # 1. Vectorized Sufficient Statistics Calculation
            # Convert hard assignments (0, 1, ..., K_new-1) into a one-hot matrix (N, K_new)
            resp = torch.nn.functional.one_hot(assignments, num_classes=K_new).float()
            
            scaling_factor = max(total_samples_seen, 1)
            
            new_S0 = resp.sum(dim=0) / scaling_factor                           # (K_new,)
            new_S1 = (resp.T @ X_valid) / scaling_factor                        # (K_new, D)
            new_S_xx = (resp.T @ (X_valid ** 2)) / scaling_factor               # (K_new, D)
            
            new_S_z = torch.zeros((K_new, q_new), device=self.device)           # (K_new, q_new)
            new_S_xz = torch.zeros((K_new, self.D, q_new), device=self.device)  # (K_new, D, q_new)
            
            # Create a batch of Identity matrices scaled by new_S0
            I_q = torch.eye(q_new, device=self.device).expand(K_new, -1, -1)
            new_S_zz = new_S0.view(K_new, 1, 1) * I_q                           # (K_new, q_new, q_new)

            # 2. Handle Tensor Shape Matching (Padding)
            if q_new < self.q:
                pad_size = self.q - q_new
                new_Lambda = torch.nn.functional.pad(new_Lambda, (0, pad_size))
                new_S_z = torch.nn.functional.pad(new_S_z, (0, pad_size))
                new_S_xz = torch.nn.functional.pad(new_S_xz, (0, pad_size))
                new_S_zz = torch.nn.functional.pad(new_S_zz, (0, pad_size, 0, pad_size))
                
            elif q_new > self.q:
                pad_size = q_new - self.q
                self.Lambda.data = torch.nn.functional.pad(self.Lambda.data, (0, pad_size))
                self.S_z = torch.nn.functional.pad(self.S_z, (0, pad_size))
                self.S_xz = torch.nn.functional.pad(self.S_xz, (0, pad_size))
                self.S_zz = torch.nn.functional.pad(self.S_zz, (0, pad_size, 0, pad_size))
                self.q = q_new

            # 3. Concatenate Parameters ONCE
            self.mu = nn.Parameter(torch.cat([self.mu.data, new_mu], dim=0))
            self.Lambda = nn.Parameter(torch.cat([self.Lambda.data, new_Lambda], dim=0))
            self.log_psi = nn.Parameter(torch.cat([self.log_psi.data, new_log_psi], dim=0))

            # 4. Concatenate Sufficient Statistics ONCE
            self.S0 = torch.cat([self.S0, new_S0])
            self.S1 = torch.cat([self.S1, new_S1])
            self.S_xx = torch.cat([self.S_xx, new_S_xx])
            self.S_z = torch.cat([self.S_z, new_S_z])
            self.S_xz = torch.cat([self.S_xz, new_S_xz])
            self.S_zz = torch.cat([self.S_zz, new_S_zz])
            
            # Append 1.0 to update_counts for each new component
            new_counts = torch.ones(K_new, device=self.device)
            self.update_counts = torch.cat([self.update_counts, new_counts])

            # 5. Automatically update global mixing weights (log_pi)
            self.log_pi = nn.Parameter(torch.log(self.S0 / self.S0.sum() + 1e-10))

            self.K += K_new
            print(f"Model successfully updated! Added {K_new} components. Total (K) is now {self.K}")


    def _initialize_parameters(self, X):
        """
        Initializes parameters using K-Means++ and Local PCA to guarantee stable, 
        deterministic convergence.
        """
        N = X.shape[0]
        
        # 1. K-Means++ Initialization for Means
        centroids = [X[torch.randint(0, N, (1,), device=self.device)[0]]]
        for _ in range(1, self.K):
            dists = torch.cdist(X, torch.stack(centroids))
            min_dists = dists.min(dim=1)[0]
            probs = min_dists / min_dists.sum()
            next_idx = torch.multinomial(probs, 1)[0]
            centroids.append(X[next_idx])
            
        self.mu.data = torch.stack(centroids)
        
        # 2. Hard EM (K-Means) Refinement (5 iterations)
        for _ in range(5):
            dists = torch.cdist(X, self.mu.data)
            labels = dists.argmin(dim=1)
            for k in range(self.K):
                if (labels == k).sum() > 0:
                    self.mu.data[k] = X[labels == k].mean(dim=0)
                    
        # 3. Local PCA for Lambda and Psi Initialization
        dists = torch.cdist(X, self.mu.data)
        labels = dists.argmin(dim=1)
        
        for k in range(self.K):
            mask = labels == k
            Nk = mask.sum().item()
            
            if Nk > self.q + 1:
                X_k = X[mask] - self.mu.data[k]
                
                # Perform SVD to find principal components
                U, S, Vh = torch.linalg.svd(X_k, full_matrices=False)
                
                # Take top 'q' components
                S_q = S[:self.q]
                V_q = Vh[:self.q, :].T  # (D, q)
                
                # Scale by standard deviation
                self.Lambda.data[k] = V_q * (S_q / math.sqrt(Nk - 1)).unsqueeze(0)
                
                # Estimate specific variance (Psi) from residual reconstruction error
                X_recon = X_k @ V_q @ V_q.T
                residual_var = ((X_k - X_recon)**2).mean(dim=0)
                self.log_psi.data[k] = torch.log(torch.clamp(residual_var, min=1e-4))
            else:
                # Fallback for empty/tiny clusters
                self.Lambda.data[k] = torch.randn(self.D, self.q, device=self.device) * 0.1
                self.log_psi.data[k] = torch.log(torch.ones(self.D, device=self.device) * 1e-2)

        # 4. Initialize Mixing Proportions
        pi_init = torch.bincount(labels, minlength=self.K).float() / N
        self.log_pi.data = torch.log(pi_init + 1e-6)
    
